name: Build Hugo blog

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  build:
    runs-on: ubuntu-22.04
      
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build the blog
      run: hugo --minify

    - name: Upload generated site as artifact
      uses: actions/upload-artifact@v3
      with:
        name: public
        path: public
