

name: Build Hugo blog Terraform

on:
  push:
    branches:
      - main  # Set a branch to deploy

permissions:
   id-token: write # This is required for requesting the JWT
   contents: read  # This is required for actions/checkout

concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

env:
  AWS_REGION: 'eu-west-1'


jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
   
    
    outputs:
           s3_bucket: ${{ steps.tf_out.outputs.s3_bucket }}
           cloudFront_ID: ${{ steps.tf_out.outputs.cloudFront_ID }}
           cloudFront_domain_name: ${{ steps.tf_out.outputs.cloudFront_domain_name }}

    steps:
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with: 
            role-to-assume: ${{secrets.IAM_ROLE}}
            aws-region: ${{secrets.AWS_REGION}}

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: "1.9.7"

        #Credentials for HCP Terraform (app.terraform.io) 
       - uses: hashicorp/setup-terraform@v3 
         with: 
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


       - name: Initialize Terraform
         id: init
         run: cd terraform && terraform init

       - name: Terraform Validate
         id: validate
         run: cd terraform && terraform validate -no-color

       - name: Plan Terraform deployment
         id: plan
         run: cd terraform && terraform plan -no-color

       - name: Apply Terraform changes
         id: apply
         run: cd terraform && terraform apply -auto-approve

        #COMMENT
       - name: Capture Terraform outputs
         id: tf_out
         run: |
             echo "s3_bucket=$(terraform output -raw s3_bucket)" >> "$GITHUB_OUTPUT"
             echo "cloudFront_ID=$(terraform output -raw cloudFront_ID)" >> "$GITHUB_OUTPUT"
             echo "cloudFront_domain_name=$(terraform output -raw cloudFront_domain_name)" >> "$GITHUB_OUTPUT"


  build:
    needs: terraform
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build the blog
      run: hugo --minify

    - name: Upload generated site as artifact
      uses: actions/upload-artifact@v4
      with:
        name: tech-blog
        path: public/**

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to S3 Bucket
      run: aws s3 sync public/ s3://$S3_BUCKET --delete

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
