name: Build Hugo blog

on:
  push:
    branches:
      - main  # Set a branch to deploy
permissions:
   id-token: write # This is required for requesting the JWT
   contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build the blog
      run: hugo --minify

    - name: Upload generated site as artifact
      uses: actions/upload-artifact@v4
      with:
        name: tech-blog
        path: public/**
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with: 
        role-to-assume: ${{secret.IAM_ROLE}}
        aws-region: ${{secret.AWS_REGION}} 

    - name: Deploy to S3 Bucket
      run: aws s3 sync public/ s3://olumercy-cloud-talent-v1 --delete

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id E2D6N7IC8X60XC --paths "/*"
