name: Build Hugo blog

on:
  push:
    branches:
      - main  # Set a branch to deploy

permissions:
   id-token: write # This is required for requesting the JWT
   contents: read  # This is required for actions/checkout

concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: uubuntu-latest
    env:
      AWS_REGION: 'eu-west-1'


    steps:

       - name: checkout
         uses: actions/checkout@v3


       - name: Configure AWS credentials                    #Define the AWS OIDC credential for Githubaction
         uses: aws-actions/configure-aws-credentials@v2
         with: 
            role-to-assume: ${{secrets.IAM_ROLE}}
            aws-region: ${{secrets.AWS_REGION}}


       - name: Setup Terraform                              #Install terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: "1.9.7"

        #Credentials for HCP Terraform (app.terraform.io)
       - uses: hashicorp/setup-terraform@v3
         with:
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}



       - name: Initialize Terraform
         run: terraform init
        
       - name: Plan Terraform deployment
         run: terraform plan

       - name: Apply Terraform changes
         run: terraform apply -auto-approve



  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build the blog
      run: hugo --minify

    - name: Upload generated site as artifact
      uses: actions/upload-artifact@v4
      with:
        name: tech-blog
        path: public/**

  
      

    

    

    #- name: Deploy to S3 Bucket
    #  run: aws s3 sync public/ s3://${{secrets.NAME_S3_BUCKET}} --delete

    #- name: Invalidate CloudFront cache
    #  run: aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUDFRONT_ID}} --paths "/*"



